dist: trusty
sudo: false
notifications:
  email: false
env:
  - RELEASE_TAG="release-$TRAVIS_BUILD_NUMBER"
if: tag IS blank


jobs:
  include:
    - stage: build and publish
      language: java
      jdk: oraclejdk8
      before_install:
      - chmod +x gradlew
      install: skip
      script: ./gradlew clean build
      before_deploy:
        - git config --local user.name "Travis CI"
        - git config --local user.email "travis@example.com"
        - git tag -f $RELEASE_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: "build/libs/pal-tracker.jar"
        skip_cleanup: true
    - stage: deploy to review
      language: bash
      script:
        - echo "Downloading $RELEASE_TAG"
        - wget -P build/libs https://github.com/$GITHUB_USERNAME/pal-tracker-dep-pipeline/releases/download/$RELEASE_TAG/pal-tracker.jar
      before_deploy:
        - echo "TRAVIS_PULL_REQUEST -> $TRAVIS_PULL_REQUEST"
        - echo "TRAVIS_BRANCH       -> $TRAVIS_BRANCH"
        - echo "TRAVIS_TAG          -> $TRAVIS_TAG"
        - echo "Deploying $RELEASE_TAG"
      deploy:
        provider: cloudfoundry
        api: $CF_API_URL
        username: $CF_USERNAME
        password: $CF_PASSWORD
#        organization: $CF_ORG
#        space: $CF_SPACE
        organization: Fujitsu KnowledgeBase
        space: development
